# -*- coding: utf-8 -*-
"""Integrated Model Construction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KIrNmzeLHWlcQ92jAG4McoEQ8F4crcnY
"""

# Install the COBRApy library
!pip install cobra --quiet

# Import necessary libraries
import cobra
from cobra import Model, Reaction, Metabolite
from cobra.io import load_matlab_model, read_sbml_model
import pandas as pd
import re

# Load the enterocyte and ETEC models
ent = load_matlab_model("mmu_ENT717.mat")
etec = read_sbml_model("iETEC_1333.xml")

# Load the V. cholerae model
vc = read_sbml_model("iAM_Vc960.xml")

# Validate the V. cholerae SBML model
cobra.io.sbml.validate_sbml_model("iAM_Vc960.xml")

# Correct the formula for chitin metabolites in the V. cholerae model
vc.metabolites.get_by_id("chitin[e]").formula = "H2O(C8H13NO5)"
vc.metabolites.get_by_id("chitin[p]").formula = "H2O(C8H13NO5)"

# Rename ETEC metabolites to a consistent format (e.g., _c to [c])
for i in range(0, len(etec.metabolites)):
  s = etec.metabolites[i].id
  last  = re.findall(r'(_[a-z])$', s)
  #print(s, last)
  if last == ['_c']:
    s_new = s.replace('_c','[c]')
    #print(s_new)
  elif last == ['_e']:
    s_new = s.replace('_e','[e]')
    #print(s_new)
  else:
    s_new = s.replace('_p','[p]')
    #print(s_new)
  etec.metabolites[i].id = s_new

# -----------------------------
# Helper Functions
# -----------------------------

def get_base_id(met_id):
  # Extract metabolite base ID without model suffix
  # For example, glc_D_[e]_etec → glc_D_[e]
  if met_id.endswith("ent"):
    s = met_id.replace("_ent", "")
  elif met_id.endswith("etec"):
    s = met_id.replace("_etec", "")
  else:
    s = met_id.replace("_vc", "")
  return s

def is_extracellular(met):
  if "[u]_ent" in met.id:
    return True
  elif "[e]" in met.id and "ent" not in met.id:
    return True
  else:
    return False

def is_periplasm(met):
  return "[p]" in met.id

def is_cytoplasm(met):
  return "[c]" in met.id

# ------------------------------------------
# Step 1: Rename metabolites with model tags
# ------------------------------------------

def rename_model(model, tag):
    model = model.copy()

    for met in model.metabolites:
        met.id = f"{met.id}_{tag}"

    for rxn in model.reactions:
        rxn.id = f"{rxn.id}_{tag}"

    for gene in model.genes:
        gene.id = f"{gene.id}_{tag}"

    return model

# ------------------------------------------------------------------------------------
# Step 2: Rename extracellular metabolites as shared metabolites (from enterocyte only)
# -------------------------------------------------------------------------------------

def create_shared_from_ent(ent_model):
  shared_dict = {}

  for met in ent_model.metabolites:
    if is_extracellular(met):
      base_id = get_base_id(met.id)
      shared_id = f"{base_id}_shared"
      shared_dict[shared_id] = Metabolite(shared_id, name = met.name, compartment = "e_shared", formula = met.formula)

  return shared_dict

# Metabolite names of the shared metabolites stored in a dictionary for later comparison
def get_allowed_bases(ent_model):
  dict_m = {}
  for m in ent_model.metabolites:
   if is_extracellular(m):
    s = m.name
    dict_m[m] = s.lower()
  return dict_m

# Helper functions for matching metabolite IDs based on their base names
pattern = r"[A-Za-z]"

def extract(s):
    s = s.split("[")[0]      # remove compartment
    s = s.replace("-", "")   # remove hyphen
    return re.findall(pattern, s)

def match(s1, s2):
    return set(extract(s1)) == set(extract(s2))

# --------------------------------------------------
# Step 4: Integrate all the models into a single one
# --------------------------------------------------
def combine_models(models, shared_dict):
    combined = cobra.Model("multi_cell_system")

    # Step 1: Add all metabolites first
    for model in models:
        for met in model.metabolites:
            if met.id not in combined.metabolites:
                combined.add_metabolites([met.copy()])

    # Step 3: Add reactions
    for model in models:
        for rxn in model.reactions:

            if rxn.id.startswith("EX_"):
                continue

            new_rxn = Reaction(rxn.id)
            new_rxn.name = rxn.name
            new_rxn.lower_bound = rxn.lower_bound
            new_rxn.upper_bound = rxn.upper_bound
            new_rxn.gene_reaction_rule = rxn.gene_reaction_rule

            # Map metabolites to combined model objects
            mets = {}
            for met, coeff in rxn.metabolites.items():
                mets[combined.metabolites.get_by_id(met.id)] = coeff

            new_rxn.add_metabolites(mets)

            combined.add_reactions([new_rxn])

    # Step 2: Replace extracellular metabolites with shared ones
    for met in shared_dict.values():
      base = get_base_id(met.id)
      shared_met_id = f"{base}".split("[")[0] + "_shared"
      name = met.name
      new_met = Metabolite(shared_met_id, name = met.name, compartment = "shared", formula = met.formula)

      for m in combined.metabolites:
          if match(m.id, met.id) and is_extracellular(m):
            for r in m.reactions:
              coeff = r.get_coefficient(m)
              r.add_metabolites({new_met: coeff})
              r.add_metabolites({m: 0}, combine = False)

      ex_rxn_shared = Reaction(f"EX_{new_met.name.replace(" ", "")}")
      ex_rxn_shared.name = f"{new_met.name} Exchange - Intestine"
      ex_rxn_shared.add_metabolites({new_met: -1})
      ex_rxn_shared.lower_bound = -100
      ex_rxn_shared.upper_bound = 10
      combined.add_reactions([ex_rxn_shared])

      for model in models[1:]:
        for m in model.metabolites:

          if match(m.id, met.id) and is_periplasm(m):
            rxn_transport = Reaction(f"{m.id.replace(" ", "")}_transport")
            rxn_transport.name = f"{met.name} Transport"
            rxn_transport.add_metabolites({new_met: -1, m: 1})
            rxn_transport.lower_bound = -100
            rxn_transport.upper_bound = 100
            combined.add_reactions([rxn_transport])

      for m in models[0].metabolites:
        if match(m.id, met.id) and is_cytoplasm(m):
          rxn_transport = Reaction(f"{m.id.replace(" ", "")}_transport")
          rxn_transport.name = f"{met.name} Transport"
          rxn_transport.add_metabolites({new_met: -1, m: 1})
          rxn_transport.lower_bound = -100
          rxn_transport.upper_bound = 100
          combined.add_reactions([rxn_transport])

    # Step 4: Add genes (optional but cleaner)
    for model in models:
        for gene in model.genes:
            if gene.id not in combined.genes:
                combined.genes += [gene.copy()]

    return combined

# Function to add exchange reactions for bloodstream metabolites
def add_exchanges_bloodstream(combined, ent):
  for r in ent.reactions:
    if r.id.startswith("EX_"):
      m = list(r.metabolites.keys())[0]
      for met in combined.metabolites:
        if match(m.id, met.id) and met.compartment == "u":
          ex_rxn_u = Reaction(f"EX_{met.id.replace(" ", "")}_[u]")
          ex_rxn_u.name = f"{met.name} Exchange - Bloodstream"
          ex_rxn_u.add_metabolites({met: 1})
          ex_rxn_u.lower_bound = r.lower_bound
          ex_rxn_u.upper_bound = r.upper_bound
          if ex_rxn_u not in combined.reactions:
            combined.add_reactions([ex_rxn_u])

# Function to add dilution reactions for extracellular metabolites
def add_dilution(combined, list_models, shared_dict):
  for model in list_models:
    for m in model.metabolites: # Iterate over all metabolites
      if is_extracellular(m): # Then apply the condition
        r = Reaction(f"{m.id.split("[ ")[0]}_dilution")
        r.name = f"{m.name} Dilution"
        r.add_metabolites({m: -1})
        r.lower_bound = -10
        r.upper_bound = 10
        if r not in combined.reactions:
          combined.add_reactions([r])

# -----------------
# Model Integration
# -----------------

def integrate_models(Vc, ETEC, ent):

  Vc = rename_model(Vc, "vc")
  ETEC = rename_model(ETEC, "etec")
  ent = rename_model(ent, "ent")

  shared_dict = create_shared_from_ent(ent)
  allowed_bases = get_allowed_bases(ent)

  combined = combine_models([ent, Vc, ETEC], shared_dict)
  add_exchanges_bloodstream(combined, ent)

  add_dilution(combined, [Vc, ETEC], shared_dict)

  return combined

# Integrate the Vc, ETEC, and enterocyte models
combined = integrate_models(vc, etec, ent)

# Display the combined model object
combined

# Display a specific metabolite from the combined model
combined.metabolites[129]

# Adjust compartment names for metabolites in the combined model
for m in combined.metabolites:
  if m.compartment == "e_shared":
    continue
  if m.id.endswith("_vc"):
    m.compartment = m.compartment + "_vc"
  elif m.id.endswith("_etec"):
    m.compartment = m.compartment + "_etec"
  else:
    if m.compartment == "c_ent" or m.compartment == "u_ent":
      continue
    else:
      m.compartment = m.compartment + "_ent"

# Display the updated compartments in the combined model
combined.compartments

# Find and print information about D-glucose metabolites in the combined model
for m in combined.metabolites:
  if m.name.lower() == "d-glucose":
    print(m, m.formula)

# Find and print reactions involving maltose in the combined model
for r in combined.reactions:
  if "maltose" in r.name:
    print(r)

# Find and print exchange reactions involving maltose in the combined model
for r in combined.reactions:
  if r.id.startswith("EX_") and "maltose" in r.name.lower():
    print(r)

# Export the combined model to an SBML file
from cobra.io import write_sbml_model
write_sbml_model(combined, "combined_model.xml")

# Remove metabolites that are not involved in any reactions to clean up the model
m_remove = []
for m in combined.metabolites:
  if len(m.reactions) == 0:
    m_remove.append(m)
combined.remove_metabolites(m_remove)

# Display the cleaned combined model object
combined

# Set up and run a flux balance analysis (FBA) to optimize biomass production
model = combined.copy()
biomass_etec = model.reactions.get_by_id("BIOMASS_Ec_iJO1366_core_53p95M_etec")
atpm_ent = model.reactions.get_by_id("ATPM_ent")
biomass_vc = model.reactions.get_by_id("vch_biomass_vc")
model.objective = {biomass_etec: 0.3, biomass_vc: 0.7}
sol = model.optimize()
print(sol.status, sol.objective_value)
rxns = ["vch_biomass_vc", "ATPM_ent", "BIOMASS_Ec_iJO1366_core_53p95M_etec"]
for r in rxns:
  print(sol.fluxes[r])
print(sol.fluxes["HEX1_ent"])

# Perform Flux Variability Analysis (FVA) on key reactions
from cobra.flux_analysis import flux_variability_analysis

fva = flux_variability_analysis(model, fraction_of_optimum = 0.85, reaction_list=["ATPM_ent", "BIOMASS_Ec_iJO1366_core_53p95M_etec", "vch_biomass_vc"])

print(fva)

fva_1 = flux_variability_analysis(model, fraction_of_optimum = 0.8)

# Find and print reactions involving D-glucose in the enterocyte part of the model
for m in combined.metabolites:
  for r in m.reactions:
    if "d-glucose" in r.name.lower() and "ent" in r.id:
      print(r)

# Display the compartments of the original enterocyte model
ent.compartments

# Download the exported combined SBML model file
from google.colab import files
files.download("combined_model.xml")

# Import matplotlib for plotting
from matplotlib import pyplot as plt

# Import the random module
import random

# Function to plot the correlation between ETEC and VC biomass fluxes under varying conditions
def plot_microbes(model):
  weights = [i/20 for i in range(0, 20)]
  etec_bm = []
  vc_bm = []
  atpm = []
  for w in weights:
    model_temp_1 = model.copy()
    biomass_etec = model_temp_1.reactions.get_by_id("BIOMASS_Ec_iJO1366_core_53p95M_etec")
    model_temp_1.objective = biomass_etec
    sol_temp_1 = model_temp_1.optimize()

    model_temp_2 = model.copy()
    biomass_vc = model_temp_2.reactions.get_by_id("vch_biomass_vc")
    biomass_etec = model_temp_2.reactions.get_by_id("BIOMASS_Ec_iJO1366_core_53p95M_etec")
    model_temp_2.reactions.get_by_id("ATPM_ent").lower_bound = sol_temp_1.objective_value * 0.85
    model_temp_2.objective = {biomass_vc: w, biomass_etec: 1 - w}
    sol_temp_2 = model_temp_2.optimize()
    etec_bm.append(sol_temp_2.fluxes["BIOMASS_Ec_iJO1366_core_53p95M_etec"])
    vc_bm.append(sol_temp_2.fluxes["vch_biomass_vc"])

  plt.plot(vc_bm, etec_bm, "-o")
  plt.title("Correlation between ETEC and VC Biomass Fluxes")
  plt.xlabel("VC Biomass Flux")
  plt.ylabel("ETEC Biomass Flux")
  plt.show()

# Call the plot_microbes function with the combined model
plot_microbes(combined)

# Perform parsimonious Flux Balance Analysis (pFBA)
sol = cobra.flux_analysis.parsimonious.pfba(model, objective = {atpm_ent: 0.1, biomass_etec: 0.45, biomass_vc: 0.45}, fraction_of_optimum = 0.8)

# Display the ETEC biomass flux from the pFBA solution
sol["BIOMASS_Ec_iJO1366_core_53p95M_etec"]

# Create a dictionary of exchange reaction bounds for the shared medium
dict_medium = {}
for m in combined.metabolites:
  if m.compartment == "shared_ent":
    for r in m.reactions:
      if "EX_" in r.id and not r.id.endswith("[u]"):
        dict_medium[r.id] = r.upper_bound
for r in combined.reactions:
  if r.id.endswith("dilution[e]"):
    dict_medium[r.id] = r.upper_bound
dict_medium

# Display the number of reactions in the medium dictionary
len(dict_medium)

# Perform a two-step optimization to determine individual and community objectives
model_1 = combined.copy()
model_1.objective = "ATPM_ent"
sol_1 = model_1.optimize()
biomass_max = sol_1.objective_value
#print(biomass_max)
alpha = 0.8
model_2 = combined.copy()
biomass_etec = model_2.reactions.get_by_id("BIOMASS_Ec_iJO1366_core_53p95M_etec")
biomass_vc = model_2.reactions.get_by_id("vch_biomass_vc")
model_2.objective = {biomass_etec: 0.5, biomass_vc: 0.5}
model_2.reactions.get_by_id("ATPM_ent").lower_bound = biomass_max * 0.8
sol_2 = model_2.optimize()
etec_biomass = sol_2.objective_value
print(sol_2.fluxes["BIOMASS_Ec_iJO1366_core_53p95M_etec"])
print(sol_2.fluxes["vch_biomass_vc"])
print(sol_2.fluxes["ATPM_ent"])

# Import pandas for data manipulation
import pandas as pd

# Create DataFrames from flux solutions and merge them
sol1_df = pd.DataFrame.from_dict(sol_1.fluxes)
sol1_df.rename(columns = {'fluxes': 'fluxes_1'}, inplace = True)
sol2_df = pd.DataFrame.from_dict(sol_2.fluxes)
sol2_df.rename(columns = {'fluxes': 'fluxes_2'}, inplace = True)
merged_df = pd.concat([sol1_df, sol2_df], axis = 1)

# Identify reactions with significant flux differences between the two optimization scenarios
list_df = []
for i in range(len(merged_df)):
  row = merged_df.iloc[i]
  row_name = row.name
  diff = abs(row[0] - row[1])
  if diff > 120:
    temp = {"Reaction ID": row_name, "Flux 1": row[0], "Flux 2": row[1], "Difference": diff, "Reaction": combined.reactions.get_by_id(row_name), "Reaction Name": combined.reactions.get_by_id(row_name).name}
    list_df.append(temp)
major_rxns = pd.DataFrame(list_df)
major_rxns

# Save the major reactions to a CSV file
major_rxns.to_csv('major_reactions.csv', index=False)

# Download the CSV file containing major reactions
files.download("major_reactions.csv")

